# fly.toml app configuration file generated for depressed-tiktok-bot on 2023-10-12T19:13:04+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "depressed-tiktok-bot"
primary_region = "waw"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
